### ISSUE TITLE
T1588.003 in solarigate -> UNC2452.json is not included in ATT&CK v8.2

### ISSUE THREAD

**Issue by rmasuoka** [center-for-threat-informed-defense/public-resources#2]
I am wondering why T1588.003 (Code Signing Certificates) in solarigate -> UNC2452.json is not included in the latest ATT&CK v8.2. Is there a reason behind it?

**Comment by adampennin** [comment]
Good catch. We'd originally mapped to  T1588.003 because of the malware being signed with legitimate certificates, but switched to just T1553.002 when subsequent reporting showed that they'd gotten their code signed as part of the build process and don't appear to have obtained the certificate. We're looking at updating the layer file here to match the small number of changes that happened between it and v8.2.

**Comment by rmasuoka** [comment]
Thanks. Mystery solved! By the way, my colleague was the one who caught the discrepancy.
